### ISSUE TITLE
showMessageClassOnParent not working

### ISSUE THREAD

**Issue by kleinpetr** [Robyer/nette-live-form-validation#10]
For example:

```
<div class="form-group col-md-6">
     {label mobile /}
     <div class="input-group">
          <span class="input-group-addon">+{$dialingCode}</span>
          {input mobile class=>'form-control'}
     </div>
</div>
```

![snimek obrazovky 2016-02-16 v 10 51 42](https://cloud.githubusercontent.com/assets/17269309/13072768/5de3da78-d49b-11e5-8d4b-bde2fd780a1a.png)

Error message is inside .input-group but I set parent to .form-group

**Comment by Robyer** [comment]
Show me your whole configuration object of liveformvalidation, please.

**Comment by kleinpetr** [comment]
I downloaded latest version and I didn't change anything.

**Comment by Robyer** [comment]
Aha, it's because the mentioned option is for **message's CLASS** to show on Parent, not **message itself**.

I added another option for that. So, try new version please, and make sure you set **messageParentClass** option to **form-group**. Then it would hopefully work.

**Comment by kleinpetr** [comment]
Console writes me: Uncaught SyntaxError: Unexpected token { on line 281 where is the condition to messageParentClass.

**Comment by Robyer** [comment]
Commited the missing bracket, thanks for report. :)
