### ISSUE TITLE
Bootstrap 3 - input-group

### ISSUE THREAD

**Issue by spernica** [Robyer/nette-live-form-validation#11]
There is an error in bootstrap 3 with input-group. Is it possible to change placeholder to only one element?

```
<div class="form-group">
   {label test /}
   <div class="input-group">
      {input test, class => 'form-control'}
      <span class="input-group-addon">m<sup>2</sup></span>
	{* sem se prida error message coz je spatne *}
   </div>
   {* spravne umisteni *}
</div>
```

**Comment by Robyer** [comment]
I believe you can use this workaround for now - manually create the message element by setting the "data-lfv-message-id" attribute containing the id of your message element.

So this should work:
```
<div class="form-group">
   {label test /}
   <div class="input-group">
      {input test, class => 'form-control', data-lfv-message-id => 'MY_FORM_TEST_MESSAGE_ID'}
      <span class="input-group-addon">m<sup>2</sup></span>
    {* sem se prida error message coz je spatne *}
   </div>
   {* spravne umisteni *}   
   <span id="MY_FORM_TEST_MESSAGE_ID"></span>
</div>
```
I'm just not sure about the syntax of setting that data- attribute.

In future I might add special data- attribute containing the class of message's parent element, so you won't need to specify it yourself as in this example.

**Comment by spernica** [comment]
Thanks! I wasn't sure if something like this exists, your example works well.
