### ISSUE TITLE
Ako vypnem validáciu pri onchange

### ISSUE THREAD

**Issue by camohub** [Robyer/nette-live-form-validation#12]
Dá sa vypnúť validácia pri onchange resp. onblur. Aby sa validovalo, iba pri submite?

**Comment by Robyer** [comment]
Můžeš ji vypnout na konkrétních prvcích přidáním speciální třídy, která je konfigurovaná vlastností `disableLiveValidationClass` - ve výchozím nastavení je to `no-live-validation`.

Pokud to chceš vypnout pro všechny, můžeš buď zkusit "hack", že nakonfiguruješ tu třídu na `.*`, takže to bude validní pro (tedy ignorovat) všechny elementy, které mají aspoň nějakou třídu.

Nebo můžeš přepsat/zakázat funkci `LiveForm.setupHandlers = function(el) { ... }`, aby nic nedělala, tzn. vůbec se nenavážou ty onchange, onblur,... callbacky.

**Comment by camohub** [comment]
Skúsil som všetky tri možnosti. Síce fungujú, ale prestane fungovať zobrazovanie erorov pri inputoch. Začne to zobrazovať v alertoch. Nevidím, že by setupHandler mal na to nejaký dosah. 

Chcelo by to nejaký user friendly prepínač tých eventov, ktoré sa majú spustiť.

**Comment by camohub** [comment]
Sorry oprava, keď použijem ```LiveForm.setupHandlers = function(el) {};``` tak to funguje tak ako chcem. 
Len mi nieje jasné, či niečo nestratím tým zmazaním setupHandleru. Nebude lepšie len prepísať change na submit a zmazať blur?

**Comment by Robyer** [comment]
Nepřijdeš o nic - jen o ten onchange/blur/keyup na všech prvcích - tedy přesně to, co jsi chtěl. "submit" celého formuláře má vlastní handler, takže nemusíš nikde nic měnit.

**Comment by camohub** [comment]
Ok díky.
