### ISSUE TITLE
Bootstrap input groups bug

### ISSUE THREAD

**Issue by misaon** [Robyer/nette-live-form-validation#14]
If you use classic input group in Bootstrap, error message (<span>) not show correctly.

**Comment by Robyer** [comment]
Could you show me some live example? (URL or just simple HTML page + JS that I can just open)

**Comment by misaon** [comment]
```
<div class="col-xs-12 col-sm-8 form-group">
	<label n:name="name">{_lang.text.name}</label>
	<div class="input-group">
		<span class="input-group-addon">
			<i class="fa fa-book"></i>
		</span>
		<input n:name="name" class="form-control">
	</div>
</div>
```

![snimek obrazovky porizeny 2016-04-11 10-30-17](https://cloud.githubusercontent.com/assets/15806356/14421297/1b71a9ac-ffd1-11e5-8488-b4b82aa76d8e.png)

**Comment by Robyer** [comment]
With default settings it put the error message after `<div class="input-group">...</div>` which is correct. You have problems with your (Bootstrap's) CSS styles.

So what is your expected result? Where do you want to have that error message element?
