### ISSUE TITLE
RadioList, CheckboxList: validation error is removed only on selecting first item

### ISSUE THREAD

**Issue by rolandtoth** [Robyer/nette-live-form-validation#15]
When using RadioList or CheckboxList, the validation error goes away only if I select the first input. Also, the error spans doesn't populate, except the first one (but maybe this is intentional).

I'm using the default renderer:

```php
$choices = array(
    'a'    => 'aaa',
    'b'   => 'bbb',
    'c'         => 'ccc'
);
$form->addCheckboxList('my_choices', 'Please select'), $choices)
    ->setRequired('Required field');
```
Am I doing something wrong?

**Comment by Robyer** [comment]
Sorry, I don't have time to deal with this, so if you can make it work and provide pull request, that would be great.

Maybe it's because internally I'm using old netteForms.js (I haven't checked lately if there were any changes) or it just needs special handling of these *List elements.

**Comment by rolandtoth** [comment]
Ok, I will get into this when I'll have some time.

If I replace the NetteForms.js part in the code, the problem still exists. Maybe it's in the original code? I have no Nette projects where I can try this (using Nette Forms as standalone).

**Comment by rolandtoth** [comment]
Here is a quick fix but I'm not sure how general is this:
https://github.com/Robyer/nette-live-form-validation/compare/master...rolandtoth:patch-1

This finds the first error message tag and empties that.

I don't understand why are there several error messages on RadioList/CheckboxList controls and not just only one. Is this by design? Can a radio or a checkbox item validated individually inRadioList/CheckboxList controls?

**Comment by Robyer** [comment]
> I don't understand why are there several error messages on RadioList/CheckboxList controls and not just only one.

Because LiveFormValidation wasn't prepared for that (when original author created it, such elements wasn't supported in Nette).

I pushed correct fix, along with updated internal netteForms.js.

Try version 1.7.0 :)

**Comment by rolandtoth** [comment]
Thanks, seems to work fine at first sight.

Btw, the error message IDs for multi elements start with "-" (eg. "-areas_message"). Is this intentional? Looks weird but according to the specs it should be valid in HTML5.

**Comment by Robyer** [comment]
> Btw, the error message IDs for multi elements start with "-" (eg. "-areas_message").

Does your form has ID? I'm creating new id as formId + "-" + elemName.

**Comment by rolandtoth** [comment]
No, there's no form ID.

**Comment by rolandtoth** [comment]
I guess that's because I use Nette Forms standalone. I see there's a "frm-..." ID when using the framework. Maybe you could add "frm" prefix if there's no ID?

**Comment by Robyer** [comment]
What ID do you see for your inputs (e.g. if you have name="areas")?
I can use "frm" or no prefix at all. I'm not sure what's better.

**Comment by rolandtoth** [comment]
Here you can view the form:
http://mosolygo.paqartdesign.com/en/contacts/be-our-volunteer/

**Comment by Robyer** [comment]
Aha, I think it would be better (and safer) to use ID for your forms. Maybe it will also automatically prefix all your input ids (as FW does it)?

Anyway, I'll keep it without "frm" prefix for now.

**Comment by rolandtoth** [comment]
All right, thanks for your inputs :) No, there's no auto prefixing when there's an ID but that no problem.

**Comment by jaroslavlibal** [comment]
Ï'm reopening this issue as the problem occurs again in the v1.9.0.

When I downgrade to the v1.8.1 then it works as expected.
