### ISSUE TITLE
add method to remove icon from help block

### ISSUE THREAD

**Issue by misaon** [Robyer/nette-live-form-validation#16]
Hi, please add method for this. I using font-awesome instead of glyphicon and i have useless class in my code.

Thanx

**Comment by Robyer** [comment]
Hi, feel free to send pull request. I don't have too much time these days.

**Comment by rolandtoth** [comment]
I use this to remove:

```javascript
if (window.LiveForm) {
    LiveForm.setOptions({
        'messageErrorPrefix': ''
    });
}
```

**Comment by Robyer** [comment]
Aha, thanks for mentioning that.

@misaon If you don't want to see any prefix, just set it empty in LiveForm options, as mentioned above. Or set it regarding your needs, just look at [live-form-validation.js](https://github.com/Robyer/nette-live-form-validation/blob/master/live-form-validation.js#L42) source code for example.
