### ISSUE TITLE
Decimals

### ISSUE THREAD

**Issue by Studioartcz** [Robyer/nette-live-form-validation#19]
Hi,

if i have input[type=number] and want type decimal format number, validator returning "Please enter a valid value". I am also set: "step=0.5" and without change.

**Comment by Robyer** [comment]
Hi, probably included code of netteForms.js must be updated (if that works in official netteForms.js).

**Comment by Studioartcz** [comment]
Thanks

**Comment by Robyer** [comment]
Commited update, please try it and let me know if everything works as before as I didn't tested it.

**Comment by Studioartcz** [comment]
No change.

**Comment by Robyer** [comment]
Could you check how it works in original netteForms.js? It should behave the same. So eventually you might want to create issue there,

**Comment by Studioartcz** [comment]
I think that with "step" attribute it is fine.

**Comment by Robyer** [comment]
Ok, so I'm closing this.
