### ISSUE TITLE
Nette 2.3 a 2.4 nefunguje toggle funkce

### ISSUE THREAD

**Issue by daremachine** [Robyer/nette-live-form-validation#20]
Nefunguje skrývání a zobrazování polí podle id na nette form toggle.
Stejný problém má někdo i na fóru. 
https://forum.nette.org/cs/25860-toggle-na-formulari-nefunkcni
https://forum.nette.org/cs/25101-toggle-nefunkcni-netteforms-js

**Comment by Robyer** [comment]
Ahoj, nejdříve je potřeba zjistit, zda je chyba v originálním netteForms.js kódu bez použití LiveFormValidatoin, tedy použij pouze - https://github.com/nette/forms/blob/master/src/assets/netteForms.js 

Pokud je chyba tam, nahlas a řeš to s nimi, a až se to opraví, dej vědět, ať můžu znovu zaintegrovat jejich změny do tohoto LiveFormValidation skriptu.

**Comment by VaclavSir** [comment]
V originálním netteForms.js toggle funguje, teď jsem to zkoušel.

**Comment by VaclavSir** [comment]
Teď jsem zkusil poslední verzi i tohoto a taky mi to funguje, takže tohle issue je asi na close.

**Comment by Robyer** [comment]
To jsem rád, že i tento skript už funguje :)
