### ISSUE TITLE
Ajax forms are sended without beign validated

### ISSUE THREAD

**Issue by Lexinek** [Robyer/nette-live-form-validation#24]
Nette 2.3 - works with original netteForms.js (alert window appears), with live-form-validation form is sent instantly.

**Comment by Lexinek** [comment]
As workaround, this extension is working for me:
```javascript
$.nette.ext('ajaxForms', {
	before: function (jqXHR, settings) {
		if (settings.nette && settings.nette.form) {
			return Nette.validateForm($(settings.nette.form)[0]);
		}
	}
});
```

Although i think it should be working by default, as with netteForms.js everything works fine.

**Comment by Robyer** [comment]
Could you prepare me live example of the problem via http://jsbin.com/ ?

**Comment by Robyer** [comment]
Btw current version of LiveFormValidation is based on netteForms.js from Nette/Forms v2.4
Better check if it's not problem of the incompatible 2.3/2.4 versions.

**Comment by Lexinek** [comment]
Ok i will try.

**Comment by Lexinek** [comment]
Oh my god, i found out what is wrong when playing around.
When using master of vojtech-dobes/nette.ajax.js live-form-validation does not work with ajax, but with stable 2.1.0/2.0.0 everything is ok!

**Comment by Robyer** [comment]
So question is now whether it should be fixed in nette.ajax.js or in live-form-validation.js.
Let me know or send PR if/when you find out what's wrong exactly.
