### ISSUE TITLE
Little problem with form validation

### ISSUE THREAD

**Issue by Pub4Game** [Robyer/nette-live-form-validation#27]
How can I disable the check field if it is not filled?

```
LiveForm.setOptions({
            showValid: true,
            wait: 1500,
            messageErrorClass: 'text-danger',
});
```

EMAIL form:
```
$form->addText('email', '')
			->setType('email')
			->setRequired('Need email')
			->setAttribute('placeholder', 'Введите ваш email')
			->addCondition($form::FILLED)
			->addRule(Form::EMAIL, 'Nope :)');
```
Because I get the following
![image](https://cloud.githubusercontent.com/assets/11244874/19892981/7eef5a7e-a058-11e6-88b9-8dfef4d8642d.png)

And need

![image](https://cloud.githubusercontent.com/assets/11244874/19893046/d3d6aac4-a058-11e6-98eb-3ef239339571.png)

Also... How can I display all the errors, if someone clicks the button "Register" and filled out all the fields?

Thank you, waiting for an answer!

**Comment by Robyer** [comment]
Commited - https://github.com/Robyer/nette-live-form-validation/commit/35a033326e90b05e88d5508c30de8cb2b26c1f63

And about your last question I don't understand what do you want to achieve exactly..

**Comment by Pub4Game** [comment]
Thank you very much!

For example, I went to the registration page and just clicked on the "Sign up" (Not filled field). It is necessary that all fields became red.

**Comment by Robyer** [comment]
Do you mean this option? It is enabled by default and works for me:

`showAllErrors	- show all errors when submitting form; or use "false" to show only first error`

**Comment by Pub4Game** [comment]
Strangely, even after your fixes I get a valid empty fields

Yes. I don't getthe errors..

**Comment by Pub4Game** [comment]
Maybe because I use `addCondition($form::FILLED)` ? How can I make a field that was checked only when the field is filled with symbols?

**Comment by Robyer** [comment]
Show me your form here so I can see the problems directly.

https://jsbin.com/qojixibule/edit?html,js,output

**Comment by Pub4Game** [comment]
```
$form = new Form;

		$form->addText('username', '')
			->setAttribute('placeholder', 'userLogin')
			->addCondition($form::FILLED)
			->setRequired('Need login')
			->addRule(Form::MIN_LENGTH, 'username must be longer than %d characters', 4);

		$form->addText('email', '')
			->setType('email')
			->setAttribute('placeholder', 'test@gmail.com')
			->addCondition($form::FILLED)
			->setRequired('Need email')
			->addRule(Form::EMAIL, 'Nope!');

		$form->addPassword('password', '')
			->setAttribute('placeholder', 'Password')
			->addCondition($form::FILLED)
			->setRequired('Need pass')
			->addRule(Form::MIN_LENGTH, 'Password must be at least %d characters', 6);

		$form->addCheckbox('agreement', '')
			->setRequired('Must read...')
			->addRule(Form::EQUAL, 'You must accept', TRUE);

		$form->addProtection('The session lifetime has expired. Try again');

		$form->addSubmit('send', '');

		$form->onValidate[] = function (Form $form, $values) {
			//my auth
		};

		$form->onSuccess[] = function (Form $form, $values) {
			//my auth
		};
```

**Comment by Pub4Game** [comment]
I don't really understand what you want... Look, I did right?

**Comment by Robyer** [comment]
Yes, that's what I wanted. You have (at least) 2 problems there:

1) From looking at JavaScript console you can see that it throws exception when parsing some json, after further digging you can see that it is problem with your "username" input's rules.

```
[{"op":":filled","rules":[{"op":":filled","msg":"Please, enter login"},{"op":":minLength","msg":"Login must be longer than 4 characters","arg":4},{"op":":maxLength","msg":"
Login should be no longer than 15 characters","arg":15}],"control":"username"}]
```
Problem is that you have new line right `"msg":<HERE>Login should be`. So then the whole script stops working. When you fix it, you will see that script starts validating your form correctly.

2) Your form works exactly like you defined it. It doesn't show errors when submitting form without filling any input because you set it that way. You probably have (as I also saw in your deleted comment) `addText(...)->addCondition(FILLED)->setRequired()->addRule(...)` which means _If input is filled (and only if it is filled), then check the rules._ Just remove the `addCondition(Form::FILLED) at the start and it will work as expected.`

**Comment by Robyer** [comment]
Here is working example: https://jsbin.com/pidukoqova/edit?html,js,output

Also you probably want to have `setRequired()` on the checkbox too.

**Comment by Pub4Game** [comment]
But if I remove the addCondition(Form::FILLED), then the field will be checked even when not filled.

It looks very pathetic when a person clicks on the field, and then in another place and the field becomes red

**Comment by Pub4Game** [comment]
https://youtu.be/KOD3eiE0F5w

I think it will be easier to explain. 

I need if the field is empty, it has not been checked

**Comment by Robyer** [comment]
What are you talking about? Think about it this way:

a) Is the input required to be filled? If yes, then remove addCondition() and keep only setRequired() (and addRule()).
b) Isn't the input required to be filled? Then you can successfully submit the form without writing anything in the input. So, when you submit empty form, it will be submitted successfully without error messages.

Also, if person clicks out of some required field, only then this certain input will become red. Not any other field in another place, only the input user worked with.

**Comment by Pub4Game** [comment]
Okay, thank you.
