### ISSUE TITLE
Setting options without editing live-form-validation.js

### ISSUE THREAD

**Issue by rolandtoth** [Robyer/nette-live-form-validation#7]
As I see there's no way to set options without editing "live-form-validation.js". It would be handy to be able to set custom options outside the js file, so one could copy the original js to another project or use different options on forms within one project.

I can share my working code if you're interested. It extends LiveForm.options with a user-defined options object.

**Comment by Robyer** [comment]
Hi, it would be great if you can share your code as pull request.

**Comment by rolandtoth** [comment]
Done:
https://github.com/Robyer/nette-live-form-validation/pull/8

**Comment by Robyer** [comment]
Thanks for that.

I realized better way of doing it. See b0a277e4b16e0c953399bb34c139c779a2d4795f and updated readme.
