### ISSUE TITLE
Another font for icons

### ISSUE THREAD

**Issue by Studioartcz** [Robyer/nette-live-form-validation#9]
Hi,

i am tring change font of icon by class, but not working:
```
<script type="text/javascript" src="../system/vendor/nette/forms/src/assets/live-form-validation.js">
<script type="text/javascript">

    LiveForm.setOptions({
        messageErrorPrefix: '&nbsp;<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;'
    });

</script>
```
Is right?
Thanks

**Comment by Robyer** [comment]
Hi,
I think that should work. What's the real result? Some error or it uses original prefix? Or...?

**Comment by Studioartcz** [comment]
Yea, it show original Options, without change.

**Comment by Robyer** [comment]
I tried it in my test project and it works correctly. Are you sure you have most recent version? Download e.g. from https://github.com/Robyer/nette-live-form-validation/archive/v1.6.1.zip

**Comment by Studioartcz** [comment]
Thanks, i was have 1.5.x version. Now it works.
